-- ============================================================
-- SP_INS_WEEK_SHIP_POPUP: 출하 팝업 데이터 추출 프로시저
--
-- 상세 문서: docs/db/ins/week/41.shipment-popup.md
--
-- 데이터 구조:
--   - TS_INS_WEEK_SUB (GUBUN='SHIP', SUB_GUBUN='STAT'): 출하 요약 통계
--   - TS_INS_WEEK_SUB (GUBUN='SHIP', SUB_GUBUN='ROW'): 일별 크로스탭 행
--   - TS_INS_WEEK_SUB (GUBUN='SHIP', SUB_GUBUN='CHART'): 일별 차트
--   - TS_INS_WEEK_SUB (GUBUN='SHIP', SUB_GUBUN='SCATTER'): 산점도
--
-- ★ 실행 순서: 이 파일을 먼저 실행 후 01_SP_INS_WEEK_MAIN.sql 실행
-- ★ 의존 테이블: TM_LPD_DATA (도축 출하 데이터)
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INS_WEEK_SHIP_POPUP (
    P_MASTER_SEQ    IN  NUMBER,
    P_JOB_NM        IN  VARCHAR2,
    P_FARM_NO       IN  INTEGER,
    P_LOCALE        IN  VARCHAR2,
    P_DT_FROM       IN  VARCHAR2,
    P_DT_TO         IN  VARCHAR2,
    P_NATIONAL_PRICE IN NUMBER DEFAULT 0 -- 전국 탕박 평균 단가 (외부에서 계산 후 전달)
) AS
    V_LOG_SEQ       NUMBER;
    V_PROC_CNT      INTEGER := 0;
    V_YEAR_FROM     VARCHAR2(10);
    V_DT_FROM_STR   VARCHAR2(10);
    V_DT_TO_STR     VARCHAR2(10);
    V_YEAR_CNT      INTEGER := 0;
    V_YEAR_AVG      NUMBER := 0;
    V_EU_DAYS       INTEGER := 160;
    V_FARM_PRICE    NUMBER := 0;
    -- SHIP_ROW에서 추출할 값 (계산 오차 방지)
    V_WEEK_CNT      INTEGER := 0;
    V_GRADE1_CNT    INTEGER := 0;
    V_GRADE1_RATE   NUMBER := 0;
    V_WEEK_AVG      NUMBER := 0;
    V_AVG_BACKFAT   NUMBER := 0;
    -- 설정값 조회용 변수
    V_SHIP_DAY      INTEGER := 180;
    V_WEAN_PERIOD   INTEGER := 21;
BEGIN
    SP_INS_COM_LOG_START(P_MASTER_SEQ, P_JOB_NM, 'SP_INS_WEEK_SHIP_POPUP', P_FARM_NO, V_LOG_SEQ);

    -- 설정값 조회 (SP_INS_WEEK_CONFIG에서 저장한 값)
    -- ★ TC_CODE_SYS/TC_FARM_CONFIG 직접 조회 제거
    --    → TS_INS_WEEK_SUB (GUBUN='CONFIG')에서 조회
    BEGIN
        SELECT NVL(CNT_3, 180),  -- 기준출하일령
               NVL(CNT_2, 21)    -- 평균포유기간
        INTO V_SHIP_DAY, V_WEAN_PERIOD
        FROM TS_INS_WEEK_SUB
        WHERE MASTER_SEQ = P_MASTER_SEQ
          AND FARM_NO = P_FARM_NO
          AND GUBUN = 'CONFIG';
    EXCEPTION
        WHEN OTHERS THEN
            V_SHIP_DAY := 180;
            V_WEAN_PERIOD := 21;
    END;
    V_EU_DAYS := V_SHIP_DAY - V_WEAN_PERIOD;

    -- 날짜 형식 변환
    V_YEAR_FROM := SUBSTR(P_DT_TO, 1, 4) || '-01-01';
    V_DT_FROM_STR := SUBSTR(P_DT_FROM, 1, 4) || '-' || SUBSTR(P_DT_FROM, 5, 2) || '-' || SUBSTR(P_DT_FROM, 7, 2);
    V_DT_TO_STR := SUBSTR(P_DT_TO, 1, 4) || '-' || SUBSTR(P_DT_TO, 5, 2) || '-' || SUBSTR(P_DT_TO, 7, 2);

    -- 당해년도 누계 (SHIP_STAT.CNT_2용)
    SELECT NVL(COUNT(*), 0), NVL(ROUND(AVG(NET_KG), 1), 0)
    INTO V_YEAR_CNT, V_YEAR_AVG
    FROM TM_LPD_DATA
    WHERE FARM_NO = P_FARM_NO AND USE_YN = 'Y'
      AND DOCHUK_DT >= V_YEAR_FROM AND DOCHUK_DT <= V_DT_TO_STR;

    -- 내농장 단가 평균 (TM_ETC_TRADE)
    -- 계정코드 511% (비육돈매출), TOTAL_KG > 0
    SELECT NVL(ROUND(SUM(TOTAL_PRICE) / DECODE(SUM(TOTAL_KG), 0, NULL, SUM(TOTAL_KG))), 0)
    INTO V_FARM_PRICE
    FROM TM_ETC_TRADE
    WHERE FARM_NO = P_FARM_NO
      AND WK_DT BETWEEN TO_DATE(V_DT_FROM_STR, 'YYYY-MM-DD') AND TO_DATE(V_DT_TO_STR, 'YYYY-MM-DD')
      AND SUBSTR(ACCOUNT_CD, 1, 3) = '511'
      AND TOTAL_KG > 0;

    -- 기존 데이터 삭제 (GUBUN='SHIP'만 삭제 - SUB_GUBUN으로 구분)
    DELETE FROM TS_INS_WEEK_SUB
    WHERE MASTER_SEQ = P_MASTER_SEQ AND FARM_NO = P_FARM_NO
      AND GUBUN = 'SHIP';

    -- ★ SHIP/ROW 먼저 INSERT (13행을 단일 쿼리로)
    -- ★ SHIP/STAT 값은 SHIP/ROW의 합계/평균에서 추출 (계산 오차 방지)
    -- VAL_1: 합계, VAL_2: 비율(%), VAL_3: 평균
    INSERT INTO TS_INS_WEEK_SUB (
        MASTER_SEQ, FARM_NO, GUBUN, SUB_GUBUN, SORT_NO, CODE_1,
        STR_1, STR_2, STR_3, STR_4, STR_5, STR_6, STR_7,
        CNT_1, CNT_2, CNT_3, CNT_4, CNT_5, CNT_6, CNT_7, VAL_1, VAL_2, VAL_3
    )
    WITH
    DATE_LIST AS (
        SELECT TO_DATE(P_DT_FROM, 'YYYYMMDD') + LEVEL - 1 AS DT,
               TO_CHAR(TO_DATE(P_DT_FROM, 'YYYYMMDD') + LEVEL - 1, 'YYYY-MM-DD') AS DT_STR,
               LEVEL AS DAY_NO
        FROM DUAL CONNECT BY LEVEL <= 7
    ),
    -- ★ AVG_TBL: 전체 평균을 원본 데이터에서 직접 계산 (운영 SQL과 동일)
    -- BACK_DEPTH는 0 또는 NULL 제외하여 계산 (운영 SQL 로직)
    AVG_TBL AS (
        SELECT
            ROUND(AVG(NET_KG), 1) AS TOTAL_AVG_NET,
            ROUND(AVG(CASE WHEN BACK_DEPTH > 0 THEN BACK_DEPTH END), 1) AS TOTAL_AVG_BACK
        FROM TM_LPD_DATA
        WHERE FARM_NO = P_FARM_NO AND USE_YN = 'Y'
          AND DOCHUK_DT >= V_DT_FROM_STR AND DOCHUK_DT <= V_DT_TO_STR
    ),
    SHIP_DATA AS (
        -- NET_KG, BACK_DEPTH: NULL 유지 (NVL 제거) - AVG 계산 시 NULL 제외됨
        SELECT D.DAY_NO, L.NET_KG, L.BACK_DEPTH,
               L.MEAT_QUALITY, L.SEX_GUBUN
        FROM TM_LPD_DATA L
        JOIN DATE_LIST D ON L.DOCHUK_DT = D.DT_STR
        WHERE L.FARM_NO = P_FARM_NO AND L.USE_YN = 'Y'
    ),
    DAILY AS (
        SELECT DAY_NO, COUNT(*) CNT, SUM(NET_KG) TOT_NET,
               ROUND(AVG(CASE WHEN NET_KG > 0 THEN NET_KG END), 1) AVG_NET,
               ROUND(AVG(CASE WHEN BACK_DEPTH > 0 THEN BACK_DEPTH END), 1) AVG_BACK,
               SUM(CASE WHEN MEAT_QUALITY = '1+' THEN 1 ELSE 0 END) Q_11,
               SUM(CASE WHEN MEAT_QUALITY = '1' THEN 1 ELSE 0 END) Q_1,
               SUM(CASE WHEN MEAT_QUALITY = '2' THEN 1 ELSE 0 END) Q_2,
               SUM(CASE WHEN SEX_GUBUN = '암' THEN 1 ELSE 0 END) FEMALE,
               SUM(CASE WHEN SEX_GUBUN = '수' THEN 1 ELSE 0 END) MALE,
               SUM(CASE WHEN SEX_GUBUN = '거세' OR SEX_GUBUN NOT IN ('암', '수') OR SEX_GUBUN IS NULL THEN 1 ELSE 0 END) ETC
        FROM SHIP_DATA GROUP BY DAY_NO
    ),
    EU_DATA AS (
        SELECT D.DAY_NO, NVL(SUM(NVL(E.DUSU, 0) + NVL(E.DUSU_SU, 0)), 0) EU_DUSU
        FROM DATE_LIST D
        LEFT JOIN TB_EU E ON E.FARM_NO = P_FARM_NO AND E.WK_DT = TO_CHAR(D.DT - V_EU_DAYS, 'YYYYMMDD')
        GROUP BY D.DAY_NO
    ),
    BASE AS (
        SELECT D.DAY_NO, TO_CHAR(D.DT, 'MM.DD') DT_DISP,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.CNT, 0) END BUT_CNT,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.TOT_NET, 0) END TOT_NET,
               CASE WHEN A.CNT IS NOT NULL THEN A.AVG_NET END AVG_NET,
               CASE WHEN A.CNT IS NOT NULL THEN A.AVG_BACK END AVG_BACK,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.Q_11, 0) END Q_11,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.Q_1, 0) END Q_1,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.Q_2, 0) END Q_2,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.FEMALE, 0) END FEMALE,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.MALE, 0) END MALE,
               CASE WHEN A.CNT IS NOT NULL THEN NVL(A.ETC, 0) END ETC,
               NVL(E.EU_DUSU, 0) EU_DUSU,
               CASE WHEN A.CNT IS NOT NULL AND A.CNT > 0 THEN ROUND((NVL(A.Q_11, 0) + NVL(A.Q_1, 0)) / A.CNT * 100, 1) END ONE_RATIO,
               CASE WHEN NVL(E.EU_DUSU, 0) > 0 AND A.CNT IS NOT NULL THEN ROUND(NVL(A.CNT, 0) / E.EU_DUSU * 100, 1) END EU_RATIO
        FROM DATE_LIST D
        LEFT JOIN DAILY A ON A.DAY_NO = D.DAY_NO
        LEFT JOIN EU_DATA E ON E.DAY_NO = D.DAY_NO
    ),
    PIVOT_DATA AS (
        SELECT MAX(CASE WHEN DAY_NO=1 THEN DT_DISP END) D1, MAX(CASE WHEN DAY_NO=2 THEN DT_DISP END) D2,
               MAX(CASE WHEN DAY_NO=3 THEN DT_DISP END) D3, MAX(CASE WHEN DAY_NO=4 THEN DT_DISP END) D4,
               MAX(CASE WHEN DAY_NO=5 THEN DT_DISP END) D5, MAX(CASE WHEN DAY_NO=6 THEN DT_DISP END) D6,
               MAX(CASE WHEN DAY_NO=7 THEN DT_DISP END) D7,
               MAX(CASE WHEN DAY_NO=1 THEN BUT_CNT END) V1_1, MAX(CASE WHEN DAY_NO=2 THEN BUT_CNT END) V1_2,
               MAX(CASE WHEN DAY_NO=3 THEN BUT_CNT END) V1_3, MAX(CASE WHEN DAY_NO=4 THEN BUT_CNT END) V1_4,
               MAX(CASE WHEN DAY_NO=5 THEN BUT_CNT END) V1_5, MAX(CASE WHEN DAY_NO=6 THEN BUT_CNT END) V1_6,
               MAX(CASE WHEN DAY_NO=7 THEN BUT_CNT END) V1_7,
               MAX(CASE WHEN DAY_NO=1 THEN EU_DUSU END) V2_1, MAX(CASE WHEN DAY_NO=2 THEN EU_DUSU END) V2_2,
               MAX(CASE WHEN DAY_NO=3 THEN EU_DUSU END) V2_3, MAX(CASE WHEN DAY_NO=4 THEN EU_DUSU END) V2_4,
               MAX(CASE WHEN DAY_NO=5 THEN EU_DUSU END) V2_5, MAX(CASE WHEN DAY_NO=6 THEN EU_DUSU END) V2_6,
               MAX(CASE WHEN DAY_NO=7 THEN EU_DUSU END) V2_7,
               MAX(CASE WHEN DAY_NO=1 THEN EU_RATIO END) V3_1, MAX(CASE WHEN DAY_NO=2 THEN EU_RATIO END) V3_2,
               MAX(CASE WHEN DAY_NO=3 THEN EU_RATIO END) V3_3, MAX(CASE WHEN DAY_NO=4 THEN EU_RATIO END) V3_4,
               MAX(CASE WHEN DAY_NO=5 THEN EU_RATIO END) V3_5, MAX(CASE WHEN DAY_NO=6 THEN EU_RATIO END) V3_6,
               MAX(CASE WHEN DAY_NO=7 THEN EU_RATIO END) V3_7,
               MAX(CASE WHEN DAY_NO=1 THEN ONE_RATIO END) V4_1, MAX(CASE WHEN DAY_NO=2 THEN ONE_RATIO END) V4_2,
               MAX(CASE WHEN DAY_NO=3 THEN ONE_RATIO END) V4_3, MAX(CASE WHEN DAY_NO=4 THEN ONE_RATIO END) V4_4,
               MAX(CASE WHEN DAY_NO=5 THEN ONE_RATIO END) V4_5, MAX(CASE WHEN DAY_NO=6 THEN ONE_RATIO END) V4_6,
               MAX(CASE WHEN DAY_NO=7 THEN ONE_RATIO END) V4_7,
               MAX(CASE WHEN DAY_NO=1 THEN Q_11 END) V5_1, MAX(CASE WHEN DAY_NO=2 THEN Q_11 END) V5_2,
               MAX(CASE WHEN DAY_NO=3 THEN Q_11 END) V5_3, MAX(CASE WHEN DAY_NO=4 THEN Q_11 END) V5_4,
               MAX(CASE WHEN DAY_NO=5 THEN Q_11 END) V5_5, MAX(CASE WHEN DAY_NO=6 THEN Q_11 END) V5_6,
               MAX(CASE WHEN DAY_NO=7 THEN Q_11 END) V5_7,
               MAX(CASE WHEN DAY_NO=1 THEN Q_1 END) V6_1, MAX(CASE WHEN DAY_NO=2 THEN Q_1 END) V6_2,
               MAX(CASE WHEN DAY_NO=3 THEN Q_1 END) V6_3, MAX(CASE WHEN DAY_NO=4 THEN Q_1 END) V6_4,
               MAX(CASE WHEN DAY_NO=5 THEN Q_1 END) V6_5, MAX(CASE WHEN DAY_NO=6 THEN Q_1 END) V6_6,
               MAX(CASE WHEN DAY_NO=7 THEN Q_1 END) V6_7,
               MAX(CASE WHEN DAY_NO=1 THEN Q_2 END) V7_1, MAX(CASE WHEN DAY_NO=2 THEN Q_2 END) V7_2,
               MAX(CASE WHEN DAY_NO=3 THEN Q_2 END) V7_3, MAX(CASE WHEN DAY_NO=4 THEN Q_2 END) V7_4,
               MAX(CASE WHEN DAY_NO=5 THEN Q_2 END) V7_5, MAX(CASE WHEN DAY_NO=6 THEN Q_2 END) V7_6,
               MAX(CASE WHEN DAY_NO=7 THEN Q_2 END) V7_7,
               MAX(CASE WHEN DAY_NO=1 THEN FEMALE END) V8_1, MAX(CASE WHEN DAY_NO=2 THEN FEMALE END) V8_2,
               MAX(CASE WHEN DAY_NO=3 THEN FEMALE END) V8_3, MAX(CASE WHEN DAY_NO=4 THEN FEMALE END) V8_4,
               MAX(CASE WHEN DAY_NO=5 THEN FEMALE END) V8_5, MAX(CASE WHEN DAY_NO=6 THEN FEMALE END) V8_6,
               MAX(CASE WHEN DAY_NO=7 THEN FEMALE END) V8_7,
               MAX(CASE WHEN DAY_NO=1 THEN MALE END) V9_1, MAX(CASE WHEN DAY_NO=2 THEN MALE END) V9_2,
               MAX(CASE WHEN DAY_NO=3 THEN MALE END) V9_3, MAX(CASE WHEN DAY_NO=4 THEN MALE END) V9_4,
               MAX(CASE WHEN DAY_NO=5 THEN MALE END) V9_5, MAX(CASE WHEN DAY_NO=6 THEN MALE END) V9_6,
               MAX(CASE WHEN DAY_NO=7 THEN MALE END) V9_7,
               MAX(CASE WHEN DAY_NO=1 THEN ETC END) V10_1, MAX(CASE WHEN DAY_NO=2 THEN ETC END) V10_2,
               MAX(CASE WHEN DAY_NO=3 THEN ETC END) V10_3, MAX(CASE WHEN DAY_NO=4 THEN ETC END) V10_4,
               MAX(CASE WHEN DAY_NO=5 THEN ETC END) V10_5, MAX(CASE WHEN DAY_NO=6 THEN ETC END) V10_6,
               MAX(CASE WHEN DAY_NO=7 THEN ETC END) V10_7,
               MAX(CASE WHEN DAY_NO=1 THEN TOT_NET END) V11_1, MAX(CASE WHEN DAY_NO=2 THEN TOT_NET END) V11_2,
               MAX(CASE WHEN DAY_NO=3 THEN TOT_NET END) V11_3, MAX(CASE WHEN DAY_NO=4 THEN TOT_NET END) V11_4,
               MAX(CASE WHEN DAY_NO=5 THEN TOT_NET END) V11_5, MAX(CASE WHEN DAY_NO=6 THEN TOT_NET END) V11_6,
               MAX(CASE WHEN DAY_NO=7 THEN TOT_NET END) V11_7,
               MAX(CASE WHEN DAY_NO=1 THEN AVG_NET END) V12_1, MAX(CASE WHEN DAY_NO=2 THEN AVG_NET END) V12_2,
               MAX(CASE WHEN DAY_NO=3 THEN AVG_NET END) V12_3, MAX(CASE WHEN DAY_NO=4 THEN AVG_NET END) V12_4,
               MAX(CASE WHEN DAY_NO=5 THEN AVG_NET END) V12_5, MAX(CASE WHEN DAY_NO=6 THEN AVG_NET END) V12_6,
               MAX(CASE WHEN DAY_NO=7 THEN AVG_NET END) V12_7,
               MAX(CASE WHEN DAY_NO=1 THEN AVG_BACK END) V13_1, MAX(CASE WHEN DAY_NO=2 THEN AVG_BACK END) V13_2,
               MAX(CASE WHEN DAY_NO=3 THEN AVG_BACK END) V13_3, MAX(CASE WHEN DAY_NO=4 THEN AVG_BACK END) V13_4,
               MAX(CASE WHEN DAY_NO=5 THEN AVG_BACK END) V13_5, MAX(CASE WHEN DAY_NO=6 THEN AVG_BACK END) V13_6,
               MAX(CASE WHEN DAY_NO=7 THEN AVG_BACK END) V13_7,
               SUM(BUT_CNT) S_BUT, SUM(EU_DUSU) S_EU, SUM(TOT_NET) S_NET,
               SUM(Q_11) S_Q11, SUM(Q_1) S_Q1, SUM(Q_2) S_Q2,
               SUM(FEMALE) S_FEM, SUM(MALE) S_MALE, SUM(ETC) S_ETC,
               -- 일별 평균 (두수 기반, 데이터 있는 일자만)
               ROUND(AVG(BUT_CNT), 1) A_BUT,
               ROUND(AVG(CASE WHEN EU_DUSU > 0 THEN EU_DUSU END), 1) A_EU,
               ROUND(AVG(Q_11), 1) A_Q11,
               ROUND(AVG(Q_1), 1) A_Q1,
               ROUND(AVG(Q_2), 1) A_Q2,
               ROUND(AVG(FEMALE), 1) A_FEM,
               ROUND(AVG(MALE), 1) A_MALE,
               ROUND(AVG(ETC), 1) A_ETC,
               ROUND(AVG(TOT_NET), 1) A_TOT_NET,
               ROUND(AVG(AVG_BACK), 1) A_BACK,
               -- 합격율 평균 = AVG(일별 합격율) - 운영 SQL과 동일
               ROUND(AVG(ONE_RATIO), 1) A_ONE_RATIO
        FROM BASE
    ),
    ROW_DEF AS (
        SELECT 1 RN, 'BUT_CNT' CD FROM DUAL UNION ALL SELECT 2, 'EU_DUSU' FROM DUAL UNION ALL
        SELECT 3, 'EU_RATIO' FROM DUAL UNION ALL SELECT 4, 'ONE_RATIO' FROM DUAL UNION ALL
        SELECT 5, 'Q_11' FROM DUAL UNION ALL SELECT 6, 'Q_1' FROM DUAL UNION ALL
        SELECT 7, 'Q_2' FROM DUAL UNION ALL SELECT 8, 'FEMALE' FROM DUAL UNION ALL
        SELECT 9, 'MALE' FROM DUAL UNION ALL SELECT 10, 'ETC' FROM DUAL UNION ALL
        SELECT 11, 'TNET_KG' FROM DUAL UNION ALL SELECT 12, 'AVG_NET' FROM DUAL UNION ALL
        SELECT 13, 'AVG_BACK' FROM DUAL
    )
    SELECT P_MASTER_SEQ, P_FARM_NO, 'SHIP', 'ROW', R.RN, R.CD,
           P.D1, P.D2, P.D3, P.D4, P.D5, P.D6, P.D7,
           CASE R.RN WHEN 1 THEN P.V1_1 WHEN 2 THEN P.V2_1 WHEN 3 THEN P.V3_1 WHEN 4 THEN P.V4_1
                     WHEN 5 THEN P.V5_1 WHEN 6 THEN P.V6_1 WHEN 7 THEN P.V7_1 WHEN 8 THEN P.V8_1
                     WHEN 9 THEN P.V9_1 WHEN 10 THEN P.V10_1 WHEN 11 THEN P.V11_1 WHEN 12 THEN P.V12_1
                     WHEN 13 THEN P.V13_1 END,
           CASE R.RN WHEN 1 THEN P.V1_2 WHEN 2 THEN P.V2_2 WHEN 3 THEN P.V3_2 WHEN 4 THEN P.V4_2
                     WHEN 5 THEN P.V5_2 WHEN 6 THEN P.V6_2 WHEN 7 THEN P.V7_2 WHEN 8 THEN P.V8_2
                     WHEN 9 THEN P.V9_2 WHEN 10 THEN P.V10_2 WHEN 11 THEN P.V11_2 WHEN 12 THEN P.V12_2
                     WHEN 13 THEN P.V13_2 END,
           CASE R.RN WHEN 1 THEN P.V1_3 WHEN 2 THEN P.V2_3 WHEN 3 THEN P.V3_3 WHEN 4 THEN P.V4_3
                     WHEN 5 THEN P.V5_3 WHEN 6 THEN P.V6_3 WHEN 7 THEN P.V7_3 WHEN 8 THEN P.V8_3
                     WHEN 9 THEN P.V9_3 WHEN 10 THEN P.V10_3 WHEN 11 THEN P.V11_3 WHEN 12 THEN P.V12_3
                     WHEN 13 THEN P.V13_3 END,
           CASE R.RN WHEN 1 THEN P.V1_4 WHEN 2 THEN P.V2_4 WHEN 3 THEN P.V3_4 WHEN 4 THEN P.V4_4
                     WHEN 5 THEN P.V5_4 WHEN 6 THEN P.V6_4 WHEN 7 THEN P.V7_4 WHEN 8 THEN P.V8_4
                     WHEN 9 THEN P.V9_4 WHEN 10 THEN P.V10_4 WHEN 11 THEN P.V11_4 WHEN 12 THEN P.V12_4
                     WHEN 13 THEN P.V13_4 END,
           CASE R.RN WHEN 1 THEN P.V1_5 WHEN 2 THEN P.V2_5 WHEN 3 THEN P.V3_5 WHEN 4 THEN P.V4_5
                     WHEN 5 THEN P.V5_5 WHEN 6 THEN P.V6_5 WHEN 7 THEN P.V7_5 WHEN 8 THEN P.V8_5
                     WHEN 9 THEN P.V9_5 WHEN 10 THEN P.V10_5 WHEN 11 THEN P.V11_5 WHEN 12 THEN P.V12_5
                     WHEN 13 THEN P.V13_5 END,
           CASE R.RN WHEN 1 THEN P.V1_6 WHEN 2 THEN P.V2_6 WHEN 3 THEN P.V3_6 WHEN 4 THEN P.V4_6
                     WHEN 5 THEN P.V5_6 WHEN 6 THEN P.V6_6 WHEN 7 THEN P.V7_6 WHEN 8 THEN P.V8_6
                     WHEN 9 THEN P.V9_6 WHEN 10 THEN P.V10_6 WHEN 11 THEN P.V11_6 WHEN 12 THEN P.V12_6
                     WHEN 13 THEN P.V13_6 END,
           CASE R.RN WHEN 1 THEN P.V1_7 WHEN 2 THEN P.V2_7 WHEN 3 THEN P.V3_7 WHEN 4 THEN P.V4_7
                     WHEN 5 THEN P.V5_7 WHEN 6 THEN P.V6_7 WHEN 7 THEN P.V7_7 WHEN 8 THEN P.V8_7
                     WHEN 9 THEN P.V9_7 WHEN 10 THEN P.V10_7 WHEN 11 THEN P.V11_7 WHEN 12 THEN P.V12_7
                     WHEN 13 THEN P.V13_7 END,
           -- VAL_1: 합계
           CASE R.RN WHEN 1 THEN P.S_BUT WHEN 2 THEN P.S_EU WHEN 5 THEN P.S_Q11 WHEN 6 THEN P.S_Q1
                     WHEN 7 THEN P.S_Q2 WHEN 8 THEN P.S_FEM WHEN 9 THEN P.S_MALE WHEN 10 THEN P.S_ETC
                     WHEN 11 THEN P.S_NET ELSE NULL END,
           -- VAL_2: 비율(%) - 등급/성별 행만
           CASE R.RN WHEN 5 THEN CASE WHEN P.S_BUT > 0 THEN ROUND(P.S_Q11 / P.S_BUT * 100, 1) ELSE 0 END
                     WHEN 6 THEN CASE WHEN P.S_BUT > 0 THEN ROUND(P.S_Q1 / P.S_BUT * 100, 1) ELSE 0 END
                     WHEN 7 THEN CASE WHEN P.S_BUT > 0 THEN ROUND(P.S_Q2 / P.S_BUT * 100, 1) ELSE 0 END
                     WHEN 8 THEN CASE WHEN P.S_BUT > 0 THEN ROUND(P.S_FEM / P.S_BUT * 100, 1) ELSE 0 END
                     WHEN 9 THEN CASE WHEN P.S_BUT > 0 THEN ROUND(P.S_MALE / P.S_BUT * 100, 1) ELSE 0 END
                     WHEN 10 THEN CASE WHEN P.S_BUT > 0 THEN ROUND(P.S_ETC / P.S_BUT * 100, 1) ELSE 0 END
                     ELSE NULL END,
           -- VAL_3: 평균 - 모든 행 (운영 SQL 로직 적용)
           CASE R.RN WHEN 1 THEN P.A_BUT
                     WHEN 2 THEN P.A_EU
                     WHEN 3 THEN CASE WHEN P.S_EU > 0 THEN ROUND(P.S_BUT / P.S_EU * 100, 1) ELSE 0 END
                     WHEN 4 THEN P.A_ONE_RATIO  -- 운영: AVG(일별 합격율)
                     WHEN 5 THEN P.A_Q11
                     WHEN 6 THEN P.A_Q1
                     WHEN 7 THEN P.A_Q2
                     WHEN 8 THEN P.A_FEM
                     WHEN 9 THEN P.A_MALE
                     WHEN 10 THEN P.A_ETC
                     WHEN 11 THEN P.A_TOT_NET
                     WHEN 12 THEN A.TOTAL_AVG_NET   -- 운영: 총지육/출하두수 (가중평균)
                     WHEN 13 THEN P.A_BACK          -- 운영: AVG(일별 등지방 평균) (단순평균)
                     END
    FROM PIVOT_DATA P, ROW_DEF R, AVG_TBL A;

    V_PROC_CNT := V_PROC_CNT + SQL%ROWCOUNT;

    -- ★ SHIP/ROW에서 SHIP/STAT 값 추출 (tbl-shipment-daily와 동일한 값 보장)
    -- CODE_1='BUT_CNT' → 출하두수 합계/평균
    -- CODE_1='Q_11', 'Q_1' → 1+등급, 1등급 두수 합계
    -- CODE_1='AVG_NET' → 지육체중 평균 (VAL_3)
    -- CODE_1='AVG_BACK' → 등지방 평균 (VAL_3)
    SELECT NVL(MAX(CASE WHEN CODE_1 = 'BUT_CNT' THEN VAL_1 END), 0),
           NVL(MAX(CASE WHEN CODE_1 = 'Q_11' THEN VAL_1 END), 0) +
           NVL(MAX(CASE WHEN CODE_1 = 'Q_1' THEN VAL_1 END), 0),
           NVL(MAX(CASE WHEN CODE_1 = 'AVG_NET' THEN VAL_3 END), 0),
           NVL(MAX(CASE WHEN CODE_1 = 'AVG_BACK' THEN VAL_3 END), 0)
    INTO V_WEEK_CNT, V_GRADE1_CNT, V_WEEK_AVG, V_AVG_BACKFAT
    FROM TS_INS_WEEK_SUB
    WHERE MASTER_SEQ = P_MASTER_SEQ AND FARM_NO = P_FARM_NO AND GUBUN = 'SHIP' AND SUB_GUBUN = 'ROW';

    -- 1등급+ 합격율 계산
    IF V_WEEK_CNT > 0 THEN
        V_GRADE1_RATE := ROUND(V_GRADE1_CNT / V_WEEK_CNT * 100, 1);
    END IF;

    -- SHIP/STAT INSERT (SHIP/ROW 합계/평균 값 사용)
    -- CNT_1: 출하두수, CNT_2: 당해년도누계, CNT_3: 1등급+두수
    -- VAL_1: 1등급+율, VAL_2: 평균도체중, VAL_3: 평균등지방
    -- VAL_4: 내농장단가, VAL_5: 전국탕박평균단가
    -- CNT_4: 기준출하일령 (V_SHIP_DAY, 기본 180)
    -- CNT_5: 평균포유기간 (V_WEAN_PERIOD, 기본 21)
    -- CNT_6: 역산일 (V_EU_DAYS = V_SHIP_DAY - V_WEAN_PERIOD, 기본 159)
    -- STR_1: 이유일 FROM (출하시작일 - 역산일, YY.MM.DD 형식)
    -- STR_2: 이유일 TO (출하종료일 - 역산일, YY.MM.DD 형식)
    INSERT INTO TS_INS_WEEK_SUB (MASTER_SEQ, FARM_NO, GUBUN, SUB_GUBUN, SORT_NO, CNT_1, CNT_2, CNT_3, CNT_4, CNT_5, CNT_6, VAL_1, VAL_2, VAL_3, VAL_4, VAL_5, STR_1, STR_2)
    VALUES (P_MASTER_SEQ, P_FARM_NO, 'SHIP', 'STAT', 1, V_WEEK_CNT, V_YEAR_CNT, V_GRADE1_CNT, V_SHIP_DAY, V_WEAN_PERIOD, V_EU_DAYS, V_GRADE1_RATE, V_WEEK_AVG, V_AVG_BACKFAT, V_FARM_PRICE, P_NATIONAL_PRICE,
           TO_CHAR(TO_DATE(P_DT_FROM, 'YYYYMMDD') - V_EU_DAYS, 'YY.MM.DD'),
           TO_CHAR(TO_DATE(P_DT_TO, 'YYYYMMDD') - V_EU_DAYS, 'YY.MM.DD'));
    V_PROC_CNT := V_PROC_CNT + 1;

    -- SHIP/CHART INSERT (7행) - 데이터 없는 날은 NULL 저장
    INSERT INTO TS_INS_WEEK_SUB (MASTER_SEQ, FARM_NO, GUBUN, SUB_GUBUN, SORT_NO, STR_1, CNT_1, VAL_1, VAL_2)
    SELECT P_MASTER_SEQ, P_FARM_NO, 'SHIP', 'CHART', D.DAY_NO, TO_CHAR(D.DT, 'MM.DD'),
           CASE WHEN COUNT(L.FARM_NO) > 0 THEN COUNT(L.FARM_NO) END,
           CASE WHEN COUNT(L.FARM_NO) > 0 THEN ROUND(AVG(L.NET_KG), 1) END,
           CASE WHEN COUNT(L.FARM_NO) > 0 THEN ROUND(AVG(L.BACK_DEPTH), 1) END
    FROM (SELECT TO_DATE(P_DT_FROM, 'YYYYMMDD') + LEVEL - 1 DT,
                 TO_CHAR(TO_DATE(P_DT_FROM, 'YYYYMMDD') + LEVEL - 1, 'YYYY-MM-DD') DT_STR,
                 LEVEL DAY_NO FROM DUAL CONNECT BY LEVEL <= 7) D
    LEFT JOIN TM_LPD_DATA L ON L.DOCHUK_DT = D.DT_STR AND L.FARM_NO = P_FARM_NO AND L.USE_YN = 'Y'
    GROUP BY D.DAY_NO, D.DT ORDER BY D.DAY_NO;
    V_PROC_CNT := V_PROC_CNT + SQL%ROWCOUNT;

    -- SHIP/SCATTER INSERT
    INSERT INTO TS_INS_WEEK_SUB (MASTER_SEQ, FARM_NO, GUBUN, SUB_GUBUN, SORT_NO, VAL_1, VAL_2, CNT_1)
    SELECT P_MASTER_SEQ, P_FARM_NO, 'SHIP', 'SCATTER', ROWNUM, NET_KG_GRP, BACK_GRP, CNT
    FROM (SELECT ROUND(NET_KG) NET_KG_GRP, ROUND(BACK_DEPTH) BACK_GRP, COUNT(*) CNT
          FROM TM_LPD_DATA
          WHERE FARM_NO = P_FARM_NO AND USE_YN = 'Y'
            AND DOCHUK_DT >= V_DT_FROM_STR AND DOCHUK_DT <= V_DT_TO_STR
            AND NET_KG IS NOT NULL AND BACK_DEPTH IS NOT NULL
          GROUP BY ROUND(NET_KG), ROUND(BACK_DEPTH) ORDER BY 1, 2);
    V_PROC_CNT := V_PROC_CNT + SQL%ROWCOUNT;

    -- TS_INS_WEEK 업데이트
    UPDATE TS_INS_WEEK
    SET LAST_SH_CNT = V_WEEK_CNT, LAST_SH_SUM = V_YEAR_CNT,
        LAST_SH_AVG_KG = V_WEEK_AVG, LAST_SH_AVG_SUM = V_YEAR_AVG
    WHERE MASTER_SEQ = P_MASTER_SEQ AND FARM_NO = P_FARM_NO;

    COMMIT;
    SP_INS_COM_LOG_END(V_LOG_SEQ, V_PROC_CNT);

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        SP_INS_COM_LOG_ERROR(V_LOG_SEQ, SQLCODE, SQLERRM);
        RAISE;
END SP_INS_WEEK_SHIP_POPUP;
/

-- 프로시저 컴파일 상태 확인
SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS WHERE OBJECT_NAME = 'SP_INS_WEEK_SHIP_POPUP';

-- 컴파일 오류 확인
SELECT LINE, POSITION, TEXT FROM USER_ERRORS WHERE NAME = 'SP_INS_WEEK_SHIP_POPUP' ORDER BY LINE;
