-- TS_INS_WEEK 테이블에 SCHEDULE_GROUP 컬럼 추가
-- ETL 시점의 스케줄 그룹 스냅샷 저장용
-- pig3.1 카카오 발송 시 TS_INS_WEEK.SCHEDULE_GROUP 기준으로 필터링

-- 1. 컬럼 추가
ALTER TABLE TS_INS_WEEK ADD (
    SCHEDULE_GROUP VARCHAR2(10) DEFAULT 'AM7'
);

COMMENT ON COLUMN TS_INS_WEEK.SCHEDULE_GROUP IS '스케줄 그룹 (AM7:오전7시, PM2:오후2시) - ETL 시점 스냅샷';

-- 2. 기존 데이터 업데이트 (TS_INS_SERVICE의 SCHEDULE_GROUP_WEEK 값으로)
UPDATE TS_INS_WEEK W
SET SCHEDULE_GROUP = (
    SELECT NVL(S.SCHEDULE_GROUP_WEEK, 'AM7')
    FROM TS_INS_SERVICE S
    WHERE S.FARM_NO = W.FARM_NO
)
WHERE EXISTS (
    SELECT 1 FROM TS_INS_SERVICE S WHERE S.FARM_NO = W.FARM_NO
);

COMMIT;
